name: Explore Variables and Secrets
on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: lohith21@gmail.com
    IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Docker Build
        run: echo docker biuld -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Docker Login
        env:
            DOCKER_PASSWORD: "Ruvtik2014"
        run: echo docker login --username=$DOCKER_USERNAME --password=${{ env.DOCKER_PASSWORD }}

      - name: Docker Publish
        run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/$IMAGE_NAME:latest