name: Explore Variables and Secrets
on: workflow_dispatch

env:
    IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Docker Build
        run: echo docker build -t ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      - name: Docker Login
        run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Publish
        run: echo docker push ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    concurrency:
        group: prod-deploy        
        cancel-in-progress: true
    steps:
      - name: Docker Run
        run: |
          echo docker run -d -p 8080:80 ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          sleep 600s     