name: Generate ASCII Artwork
on: push
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: install Cowsay program
          run: sudo apt-get install cowsay -y
          
        - name: Execute cowsay CMD
          run: cowsay -f dragon "Run for cover, i am a DRAGON....RAWR" >>dragon.txt

        - name: Sleep for 40 seconds
          run: sleep 40

        - name: Build
          run: echo "Building ......."

    test_job:
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 20 seconds
          run: sleep 20

        - name: test if file exists
          run: grep -i "dragon" dragon.txt

        - name: Test
          run: echo "Testing ......."
          
    deploy_job:
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 20 seconds
          run: sleep 20

        - name: reat the file
          run: cat dragon.txt

        - name: Deploy
          run: echo "Deploying ......."