name: Generate ASCII Artwork
on: push
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: install Cowsay program
          run: sudo apt-get install cowsay -y
          
        - name: Execute cowsay CMD
          run: cowsay -f dragon "Run for cover, i am a DRAGON....RAWR" >>dragon.txt

        - name: Upload the file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt

        - name: Build
          run: echo "Building ......."

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
        - name: Download the file
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: test if file exists
          run: grep -i "dragon" dragon.txt

        - name: Test
          run: echo "Testing ......."
          
    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:
        - name: Download the file
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: reat the file
          run: cat dragon.txt

        - name: Deploy
          run: echo "Deploying ......."